baseurl = "https://wouter.tech/"
languageCode = "en-US"
title = "Wouter Veeken – Technical Writer in the Netherlands"
# Enable comments by entering your Disqus shortname
disqusShortname = "wouter-tech"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-96197135-1"
theme = "hugo-sustain-custom"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "20181231_135909.jpg"
  author = "Wouter Veeken"
  description = "Technical writer in the Netherlands"
  bio = "I'm a technical writer from Boxtel in the Netherlands. I enjoy the books of Terry Pratchett, the music of Paul Simon, and playing the guitar."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[Social]
  Github        = "wouter-veeken"
  Email         = "me@wouter.tech"
  LinkedIn      = "wouter-veeken"
  # Twitter       = ""
  LINE          = "veeken.wouter"
#  Stackoverflow = "username"

[params.vitae]
  website = "wouter.tech"
  website_full = "https://wouter.tech"
  # tel = "+81 0000 000000"
  # tel_full = "+440000000000"
  # google_maps = "https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL"
  # address = "44 Perth Street"
  # postcode = "EH3 5BL"
  city = "Boxtel"
  country = "The Netherlands"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
# [[menu.main]]
#   name = "resume"
#   identifier = "resume"
#   weight = 300
#   url = "/resume/"
